"""GitLab connector: fetch knowledge documents from GitLab via API.

Accepts a ``SourceConfig`` with one of the two shapes documented in the plan:

    # Whole group (recursively pulls projects, including subgroups by default)
    { "kind": "gitlab", "group_path": "platform-team", "include_subgroups": true }

    # Single project
    { "kind": "gitlab", "project_path": "platform-team/api-gateway", "ref": "main" }

What gets fetched per project:

- Every ``.md`` / ``.markdown`` / ``.rst`` file at any depth in the repo
- Root-level ``README.txt`` and ``CODEOWNERS``
- Wiki pages via the GitLab wiki API (opt out with ``include_wiki: false``)
- Project metadata (becomes the document title for READMEs)

Vendor / generated directories are filtered out before any fetch:
``node_modules/``, ``vendor/``, ``dist/``, ``build/``, ``.cache/``, ``target/``,
``.next/``, etc. There is no per-project *content* cap, but the GitLab tree
walk caps **discovery** at 2000 entries per project as a safety guard against
pathological repos with autogenerated trees.

For whole-group ingests (``group_path``), the connector adds
``last_activity_after = now - PRISM_GITLAB_GROUP_ACTIVE_WINDOW_DAYS`` (default
30 days) so dormant projects never appear in the walk. The
``PRISM_GITLAB_MAX_PROJECTS_PER_SOURCE`` cap (default 200) is a separate
blast-radius guard for thousand-project groups.

Auth fallback: per-source token > ``PRISM_GITLAB_TOKEN`` env var > no token
(public projects only). The UI no longer collects per-source tokens; the
wizard's project + group dropdowns hit ``/api/gitlab/{projects,groups}/search``
against the service-account token.

Design notes:
- Uses the synchronous ``httpx.Client`` because the surrounding pipeline is
  still synchronous during the parse/embed phases. The pipeline wraps the
  initial ``list_documents`` walk in ``asyncio.to_thread`` so a slow GitLab
  doesn't block the FastAPI event loop.
- A single ``Client`` is created per connector instance and closed via the
  ``close`` hook. That's ~1 client per ingest run.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any
from urllib.parse import quote

import httpx

from src.config import settings
from src.connectors.base import Connector, ConnectorRegistry, SourceConfig
from src.models.document import DocumentMetadata, DocumentRef, RawDocument
from src.observability.logging import get_logger

log = get_logger("gitlab_connector")


# Extensions we treat as knowledge content. Any file with one of these
# extensions is eligible regardless of directory -- a README.md buried at
# ``packages/auth/README.md`` is just as useful as ``docs/auth.md``.
KNOWLEDGE_EXTENSIONS = (".md", ".markdown", ".rst")

# Root-level text files that are conventionally knowledge but don't carry
# an extension from ``KNOWLEDGE_EXTENSIONS``. Matched case-insensitively
# against the full path.
KNOWLEDGE_ROOT_FILES = (
    "readme.txt",
    "codeowners",
)

# Directory prefixes we always skip. These are almost exclusively vendored
# third-party code whose markdown files would dilute the knowledge base
# with upstream release notes / contributor guides. Match is case-sensitive
# against path segments; ``contains``-style so ``packages/foo/node_modules/``
# is also skipped.
VENDOR_DIR_SEGMENTS = (
    "node_modules/",
    "vendor/",
    ".venv/",
    "__pycache__/",
    "dist/",
    "build/",
    ".next/",
    ".nuxt/",
    ".cache/",
    "target/",   # rust/java build output
)

# Sentinel used in the ref slot of ``source_path`` to mark a wiki page. Wiki
# pages aren't tied to a branch, so we hijack the ref field rather than adding
# a new composite delimiter. Double-underscore prefix/suffix makes accidental
# collisions with real branch names vanishingly unlikely.
WIKI_REF_SENTINEL = "__wiki__"

# Mapping from GitLab's wiki ``format`` field to our file_type extension. The
# downstream parser uses file_type to pick a reader; markdown wikis get .md,
# asciidoc gets .adoc, etc. Unknown formats fall back to .md since markdown is
# the default on gitlab.com.
_WIKI_FORMAT_TO_EXT = {
    "markdown": ".md",
    "asciidoc": ".adoc",
    "rdoc": ".rdoc",
    "org": ".org",
    "creole": ".creole",
}


class GitLabAPIError(RuntimeError):
    """Raised when the GitLab API returns a non-2xx response we can't recover from."""


class GitLabConnector(Connector):
    platform = "gitlab"

    def __init__(self, source: SourceConfig) -> None:
        super().__init__(source)

        base_url = source.config.get("base_url") or settings.gitlab_base_url
        # Per-source token takes precedence (lets operators override for a
        # specific org/group that needs a different PAT); otherwise we fall
        # back to the server-wide service-account token. The UI no longer
        # collects a per-source token, so this is the default path.
        token = source.token or settings.gitlab_token or ""
        headers = {"User-Agent": "prism-ingest/0.1"}
        if token:
            headers["PRIVATE-TOKEN"] = token
        # Keep the effective token on the instance so search_projects /
        # list_documents can still check whether we have auth.
        self._effective_token = token

        self._client = httpx.Client(
            base_url=base_url.rstrip("/"),
            headers=headers,
            timeout=settings.gitlab_request_timeout_seconds,
        )

        # Cached mapping so fetch_document doesn't re-resolve project IDs.
        # Populated lazily by list_documents().
        self._project_cache: dict[str, dict[str, Any]] = {}

    # ---- lifecycle ----

    def close(self) -> None:
        self._client.close()

    async def aclose(self) -> None:
        self.close()

    # ---- public API expected by the pipeline ----

    def list_documents(self) -> list[DocumentRef]:
        projects = self._resolve_projects()
        if not projects:
            log.warning("gitlab_no_projects_found", source=self.source.name)
            return []

        refs: list[DocumentRef] = []
        include_wiki = bool(self.source.config.get("include_wiki", True))

        for project in projects:
            project_path = project["path_with_namespace"]
            ref = self.source.config.get("ref") or project.get("default_branch") or "main"

            # Cache the project payload -- fetch_document needs the ID and
            # web URL later, and re-hitting /projects/:path is wasteful.
            self._project_cache[project_path] = project

            try:
                doc_paths = self._list_knowledge_paths(project["id"], ref)
            except Exception as e:  # noqa: BLE001
                log.error(
                    "gitlab_list_paths_failed",
                    project=project_path,
                    error=str(e)[:200],
                )
                doc_paths = []

            project_refs: list[DocumentRef] = [
                DocumentRef(
                    source_platform="gitlab",
                    # Composite path namespaces docs by project so the
                    # registry's ``source_path`` remains globally unique
                    # even when two projects both have README.md.
                    source_path=f"{project_path}@{ref}:{path}",
                    file_type=_extension_of(path),
                )
                for path in doc_paths
            ]

            if include_wiki and project.get("wiki_enabled", True):
                wiki_pages = self._list_wiki_pages(project["id"])
                for page in wiki_pages:
                    slug = page.get("slug")
                    if not slug:
                        continue
                    file_type = _WIKI_FORMAT_TO_EXT.get(page.get("format") or "", ".md")
                    project_refs.append(
                        DocumentRef(
                            source_platform="gitlab",
                            # The sentinel ref slot marks this as a wiki page;
                            # fetch_document dispatches on it. ``wiki/`` in the
                            # inner path also ensures the parser's doc_type
                            # detector classifies the chunk as ``wiki``.
                            source_path=f"{project_path}@{WIKI_REF_SENTINEL}:wiki/{slug}",
                            file_type=file_type,
                        )
                    )

            refs.extend(project_refs)

        log.info(
            "gitlab_listed",
            source=self.source.name,
            projects=len(projects),
            documents=len(refs),
        )
        return refs

    def fetch_document(self, ref: DocumentRef) -> RawDocument:
        project_path, gitref, inner_path = _parse_source_path(ref.source_path)
        project = self._project_cache.get(project_path) or self._resolve_single_project(project_path)
        project_id = project["id"]

        if gitref == WIKI_REF_SENTINEL:
            return self._build_wiki_document(ref, project, inner_path)

        content = self._fetch_file(project_id, inner_path, gitref)
        last_modified = self._last_commit_time(project_id, inner_path, gitref) or _parse_gitlab_datetime(
            project.get("last_activity_at")
        )

        title = _extract_title(inner_path, content) or project.get("name") or inner_path
        web_url = project.get("web_url", "")
        file_url = (
            f"{web_url.rstrip('/')}/-/blob/{quote(gitref, safe='')}/{inner_path}"
            if web_url
            else ""
        )

        metadata = DocumentMetadata(
            title=title,
            last_modified=last_modified,
            source_url=file_url,
            labels=project.get("topics") or [],
            extra={
                "gitlab_project_id": project_id,
                "gitlab_project_path": project_path,
                "gitlab_ref": gitref,
                "gitlab_web_url": web_url,
                "gitlab_description": project.get("description") or "",
            },
        )

        return RawDocument(ref=ref, content=content, metadata=metadata)

    def _build_wiki_document(
        self,
        ref: DocumentRef,
        project: dict[str, Any],
        inner_path: str,
    ) -> RawDocument:
        # inner_path is ``wiki/<slug>`` -- strip the prefix back to the slug
        # GitLab expects on the wiki endpoint.
        slug = inner_path.removeprefix("wiki/") if inner_path.startswith("wiki/") else inner_path
        project_id = project["id"]
        project_path = project["path_with_namespace"]

        page = self._fetch_wiki_page(project_id, slug)
        content = page.get("content") or ""
        # Wiki API has no last-modified field. Fall back to project activity,
        # matching the file-path code path's fallback.
        last_modified = _parse_gitlab_datetime(project.get("last_activity_at"))

        title = page.get("title") or _extract_title(slug, content) or slug
        web_url = project.get("web_url", "")
        wiki_url = (
            f"{web_url.rstrip('/')}/-/wikis/{quote(slug, safe='/')}"
            if web_url
            else ""
        )

        metadata = DocumentMetadata(
            title=title,
            last_modified=last_modified,
            source_url=wiki_url,
            labels=project.get("topics") or [],
            extra={
                "gitlab_project_id": project_id,
                "gitlab_project_path": project_path,
                "gitlab_wiki_slug": slug,
                "gitlab_wiki_format": page.get("format") or "markdown",
                "gitlab_web_url": web_url,
                "gitlab_description": project.get("description") or "",
            },
        )

        return RawDocument(ref=ref, content=content, metadata=metadata)

    # ---- GitLab API helpers ----

    def _resolve_projects(self) -> list[dict[str, Any]]:
        """Return the list of project dicts described by the source config.

        Dispatches on ``project_path`` vs ``group_path``. Raises
        ``GitLabAPIError`` if neither is set.
        """
        config = self.source.config

        if config.get("project_path"):
            return [self._resolve_single_project(str(config["project_path"]))]

        if config.get("group_path"):
            return self._list_group_projects(
                str(config["group_path"]),
                include_subgroups=bool(config.get("include_subgroups", True)),
            )

        raise GitLabAPIError(
            "Source config must include either 'project_path' or 'group_path'"
        )

    def _resolve_single_project(self, project_path: str) -> dict[str, Any]:
        encoded = quote(project_path, safe="")
        response = self._client.get(f"/projects/{encoded}")
        _raise_for_status(response, project_path)
        return response.json()

    def _list_group_projects(self, group_path: str, *, include_subgroups: bool) -> list[dict[str, Any]]:
        encoded = quote(group_path, safe="")
        params = [
            f"include_subgroups={'true' if include_subgroups else 'false'}",
            "per_page=100",
            "archived=false",
            "order_by=last_activity_at",
        ]
        # Skip dormant projects -- avoids ingesting old experimental forks
        # that haven't been touched in months. ``last_activity_at`` covers
        # commits, MRs, issues, releases, etc. -- the standard "active"
        # signal in GitLab. Set ``gitlab_group_active_window_days = 0`` in
        # settings to disable.
        active_days = settings.gitlab_group_active_window_days
        if active_days and active_days > 0:
            cutoff = datetime.now(tz=timezone.utc) - timedelta(days=active_days)
            params.append(f"last_activity_after={cutoff.isoformat()}")
        endpoint = f"/groups/{encoded}/projects?{'&'.join(params)}"
        return self._paginate(endpoint, limit=settings.gitlab_max_projects_per_source)

    def _list_knowledge_paths(self, project_id: int, ref: str) -> list[str]:
        """Walk the project's tree and return knowledge paths."""
        endpoint = (
            f"/projects/{project_id}/repository/tree"
            f"?recursive=true&ref={quote(ref, safe='')}&per_page=100"
        )
        try:
            entries = self._paginate(endpoint, limit=2000)
        except GitLabAPIError as e:
            # Empty repos or missing refs raise 404; treat as no docs.
            log.info("gitlab_tree_unavailable", project_id=project_id, ref=ref, error=str(e)[:200])
            return []

        paths: list[str] = []
        for entry in entries:
            if entry.get("type") != "blob":
                continue
            path = entry.get("path", "")
            if _is_knowledge_path(path):
                paths.append(path)
        paths.sort()
        return paths

    def search_projects(
        self,
        query: str = "",
        *,
        page: int = 1,
        per_page: int = 20,
    ) -> tuple[list[dict[str, Any]], bool]:
        """Search projects via ``/projects?search=…``.

        With a token we add ``membership=true`` so callers only see their own
        projects (otherwise gitlab.com returns the full public firehose).
        ``simple=true`` trims the payload to just what the picker needs.

        Returns ``(projects, has_more)``. ``has_more`` comes from the
        ``X-Next-Page`` header -- GitLab dropped ``X-Total`` on gitlab.com for
        large instances, so we can't rely on a total count.
        """
        params: list[str] = [
            "simple=true",
            # Intentionally no order_by -- gitlab.com returns a 500 when
            # ``simple=true`` is combined with ``order_by=last_activity_at``
            # for the membership listing. GitLab's default ordering is fine.
            f"per_page={max(1, min(per_page, 100))}",
            f"page={max(page, 1)}",
        ]
        if query:
            params.append(f"search={quote(query, safe='')}")
        if self._effective_token:
            params.append("membership=true")
        endpoint = f"/projects?{'&'.join(params)}"

        response = self._client.get(endpoint)
        _raise_for_status(response, "project search")
        batch = response.json()
        if not isinstance(batch, list):
            raise GitLabAPIError(
                f"Expected list from /projects, got {type(batch).__name__}"
            )
        next_page = response.headers.get("x-next-page") or response.headers.get("X-Next-Page") or ""
        has_more = bool(next_page.strip())
        return batch, has_more

    def search_groups(
        self,
        query: str = "",
        *,
        page: int = 1,
        per_page: int = 20,
    ) -> tuple[list[dict[str, Any]], bool]:
        """Search groups via ``/groups?search=…``.

        Mirrors ``search_projects`` -- with a token we scope to
        membership-only so the dropdown shows the user's groups rather
        than every public group on the instance. ``(groups, has_more)``.
        """
        params: list[str] = [
            f"per_page={max(1, min(per_page, 100))}",
            f"page={max(page, 1)}",
        ]
        if query:
            params.append(f"search={quote(query, safe='')}")
        if self._effective_token:
            # Gitlab.com's group listing respects ``min_access_level`` rather
            # than ``membership`` -- 10 = Guest, which covers anything the
            # user can see, which is what the picker wants.
            params.append("min_access_level=10")
        endpoint = f"/groups?{'&'.join(params)}"

        response = self._client.get(endpoint)
        _raise_for_status(response, "group search")
        batch = response.json()
        if not isinstance(batch, list):
            raise GitLabAPIError(
                f"Expected list from /groups, got {type(batch).__name__}"
            )
        next_page = response.headers.get("x-next-page") or response.headers.get("X-Next-Page") or ""
        has_more = bool(next_page.strip())
        return batch, has_more

    def _list_wiki_pages(self, project_id: int) -> list[dict[str, Any]]:
        """Return wiki page stubs (slug, title, format). Content is NOT fetched here.

        GitLab returns 403/404 when the wiki is disabled for a project or when
        the caller lacks read_wiki scope. Those are expected on mixed repos,
        so we log-and-return instead of letting the whole ingest fail.
        """
        endpoint = (
            f"/projects/{project_id}/wikis"
            f"?with_content=false&per_page=100"
        )
        try:
            return self._paginate(endpoint)
        except GitLabAPIError as e:
            log.info("gitlab_wiki_unavailable", project_id=project_id, error=str(e)[:200])
            return []

    def _fetch_wiki_page(self, project_id: int, slug: str) -> dict[str, Any]:
        encoded = quote(slug, safe="")
        response = self._client.get(f"/projects/{project_id}/wikis/{encoded}")
        _raise_for_status(response, f"wiki:{slug}")
        return response.json()

    def _fetch_file(self, project_id: int, path: str, ref: str) -> str:
        encoded_path = quote(path, safe="")
        endpoint = (
            f"/projects/{project_id}/repository/files/{encoded_path}/raw"
            f"?ref={quote(ref, safe='')}"
        )
        response = self._client.get(endpoint)
        _raise_for_status(response, path)
        # GitLab returns raw bytes; decode as utf-8 with replacement so binary
        # content (unlikely under docs/ but possible) still produces a string
        # the pipeline can chunk.
        return response.content.decode("utf-8", errors="replace")

    def _last_commit_time(self, project_id: int, path: str, ref: str) -> datetime | None:
        """Best-effort per-file last-modified timestamp.

        Uses the /commits endpoint filtered by path. Falls back to None if the
        repo/path is missing. The pipeline treats None as "unknown".
        """
        encoded_path = quote(path, safe="")
        endpoint = (
            f"/projects/{project_id}/repository/commits"
            f"?path={encoded_path}&ref_name={quote(ref, safe='')}&per_page=1"
        )
        try:
            response = self._client.get(endpoint)
            if response.status_code != 200:
                return None
            commits = response.json() or []
            if not commits:
                return None
            return _parse_gitlab_datetime(commits[0].get("committed_date"))
        except httpx.HTTPError as e:
            log.debug("gitlab_last_commit_failed", path=path, error=str(e)[:200])
            return None

    def _paginate(self, path: str, *, limit: int | None = None) -> list[dict[str, Any]]:
        """Follow rel=next pagination links until exhausted (or ``limit`` if set)."""
        results: list[dict[str, Any]] = []
        current = path
        while current and (limit is None or len(results) < limit):
            response = self._client.get(current)
            _raise_for_status(response, current)
            batch = response.json()
            if not isinstance(batch, list):
                raise GitLabAPIError(f"Expected list from {current}, got {type(batch).__name__}")
            results.extend(batch)
            current = _next_page_url(response)
        return results[:limit] if limit is not None else results


# ---------- module-level helpers ----------


def _is_knowledge_path(path: str) -> bool:
    # Fast reject: any vendored directory anywhere in the path.
    lowered_path = path.lower()
    for seg in VENDOR_DIR_SEGMENTS:
        if seg in lowered_path:
            return False
    # Accept any file with a knowledge extension at any depth.
    if any(lowered_path.endswith(ext) for ext in KNOWLEDGE_EXTENSIONS):
        return True
    # Accept conventional root-level text files without an extension check
    # (CODEOWNERS, README.txt) -- only at the project root.
    if lowered_path in KNOWLEDGE_ROOT_FILES:
        return True
    return False


def _extension_of(path: str) -> str:
    idx = path.rfind(".")
    return path[idx:].lower() if idx >= 0 else ""


def _extract_title(path: str, content: str) -> str:
    """Pull an H1 from markdown, otherwise humanize the filename."""
    if path.lower().endswith((".md", ".markdown")):
        for line in content.split("\n")[:10]:
            stripped = line.strip()
            if stripped.startswith("# "):
                return stripped[2:].strip()
    name = path.rsplit("/", 1)[-1]
    if "." in name:
        name = name.rsplit(".", 1)[0]
    return name.replace("-", " ").replace("_", " ").title()


def _parse_source_path(source_path: str) -> tuple[str, str, str]:
    """Undo the ``{project_path}@{ref}:{inner_path}`` encoding from list_documents."""
    if "@" not in source_path or ":" not in source_path:
        raise GitLabAPIError(f"Malformed gitlab source_path: {source_path}")
    project_path, rest = source_path.split("@", 1)
    ref, inner_path = rest.split(":", 1)
    return project_path, ref, inner_path


def _parse_gitlab_datetime(value: Any) -> datetime | None:
    if not value or not isinstance(value, str):
        return None
    # GitLab timestamps look like "2024-05-12T10:34:56.000Z".
    normalized = value.replace("Z", "+00:00")
    try:
        dt = datetime.fromisoformat(normalized)
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt


def _raise_for_status(response: httpx.Response, context: str) -> None:
    if response.status_code // 100 == 2:
        return
    body_snippet = response.text[:200] if response.text else ""
    raise GitLabAPIError(
        f"GitLab API {response.status_code} on {context}: {body_snippet}"
    )


def _next_page_url(response: httpx.Response) -> str | None:
    """Parse a GitLab ``Link`` header for the rel=next URL.

    GitLab emits absolute URLs (e.g.
    ``https://gitlab.example/api/v4/projects?page=2``). We just return them
    as-is: httpx.Client accepts absolute URLs in ``client.get()`` even when a
    ``base_url`` is configured, so the caller doesn't need to reconstruct
    relative paths.
    """
    link = response.headers.get("link") or response.headers.get("Link")
    if not link:
        return None
    for part in link.split(","):
        segments = [s.strip() for s in part.split(";")]
        if len(segments) < 2:
            continue
        url_segment = segments[0]
        rel_segments = [s for s in segments[1:] if s.startswith("rel=")]
        if not rel_segments:
            continue
        rel_value = rel_segments[0].split("=", 1)[1].strip().strip('"')
        if rel_value != "next":
            continue
        if url_segment.startswith("<") and url_segment.endswith(">"):
            url_segment = url_segment[1:-1]
        return url_segment
    return None


ConnectorRegistry.register("gitlab", GitLabConnector)
